theme: jekyll-theme-cayman
title: Welcome to Adam's Projects homepage!
description: Here I will post descriptions of the data science projects I've worked on and point out interesting things about them. 
