theme: jekyll-theme-cayman
title: Welcome to Adam Drescher's Website!
description: This webiste serves as a repository for my current project portfolio, a listing of my professional experiences, and a listing of my publication and presentation record. 
